preset: recommended

disabled:
  - braces
  - no_blank_lines_after_class_opening
  - phpdoc_separation
  - ordered_use
  - phpdoc_order
  - short_array_syntax
  - single_blank_line_before_namespace
  - single_quote
  - unary_operators_spaces
